config/routes.rb
Rails4::Application.routes.draw do
 
  resources :companies, :except => [:destroy, :show] do 
    member do 
      put :change_status
    end
  end

  scope(path: "(:current_company)") do 
    as :employee do
      match '/employee/confirmation' => 'confirmations#update', :via => :put, :as => :update_employee_confirmation
    end
    
    devise_for :employees, :controllers => { :confirmations => "confirmations" }
    
    get "employees(/:type)", :controller => :employees, :action => :index, :type => /enabled|disabled/, :as => :employees

    resources :employees, :except => :index do
      get :autocomplete_employee_name, :on => :collection
      get 'password/reset', :action => 'edit_password', :on => :collection
      put :update_password, :on => :collection
      get :assignment_report, :on => :collection
      member do
        put :disable
        put :enable
      end 
    end

    resources :assets, :path => "assets", :only => [:new, :create] do 
      member do 
        put :uploaded_files
      end
      collection do 
        get :autocomplete_tag_name
        get :autocomplete_assets_name
        get :autocomplete_asset_vendor
        get :autocomplete_asset_brand
      end
    end
    
    get "/assets(/:type)", to: "assets#index", :as => :assets_list

    resources :asset_types do 
      resources :assets do
        collection do
          get :change_form_content
          get :assign
        end
        member do
          delete :remove_tag
          put :retire_asset
        end 
        resources :assignments, :only => [:new, :create]
      end
    end

    resources :property_groups, :except => [:edit, :update] do 
      resources :properties, :only => [:create, :destroy]
    end


    resources :comments, :only => [:create, :destroy, :show]
    
    resources :asset_properties, :except => :index do 
      get :autocomplete_property_name, :on => :collection
    end

    resources :assignments do
      collection do
        get :change_aem_form
        get :populate_asset
      end
    end
    
    get "tickets(/:state)", :controller => :tickets, :action => :index, :state => /closed|open/, :as => :tickets
    get "/asset_types/:id/asset/:id/tickets", :to => "assets#tickets", :as => "asset_tickets"
    
    resources :tickets, :except => [:destroy, :edit, :update] do 
      member do 
        put :change_state
      end
      collection do 
        get :search
      end
    end
    resources :file_uploads, :only => :destroy  

    get "/:id/asset_properties", :to => "asset_properties#index", :as => "asset_properties_index"    
    get ":type/:id/return", :to => "assignments#return_asset", :as => "return_asset"
    get ":type/:id/histories", :to => "histories#index", :as => "histories"
    get 'show_tag', :to => "home#show_tag", :as => :show_tag
    get 'search', :to => "home#search", :as => :search
    get "asset_type/:asset_type_id/asset/:id/return", :to => "assignments#return_asset", :as => "return_asset_type_asset"

    authenticated :employee do
      root :to => "home#index"
    end

    unauthenticated :employee do
      devise_scope :employee do 
        get "/" => "devise/sessions#new"
      end
    end
  end
  
end

app/models/concerns/employee/devisable.rb
class Employee
  module Devisable
    extend ActiveSupport::Concern
    
    def attempt_set_password(params)
      p = {}
      p[:password] = params[:password]
      p[:password_confirmation] = params[:password_confirmation]
      update_attributes(p)
    end
    
    # new function to return whether a password has been set
    def has_no_password?
      encrypted_password.blank?
    end

    # new function to provide access to protected method unless_confirmed
    def only_if_unconfirmed
      pending_any_confirmation {yield}
    end
    
    def password_required?
      # Password is required if it is being set, but not for new records
      if !self.persisted? 
        false
      else
        !password.nil? || !password_confirmation.nil?
      end
    end
    
    def active_for_authentication?
      eligible = has_role?(:super_admin) ? true : company.enabled?
      has_any_role? && eligible && super 
    end

    def inactive_message
      if has_any_role?
        company.enabled? ? super : :deactivated 
      else
        "Your account has been disabled"
      end
    end
  end
end

app/models/concerns/employee/manage_role.rb
class Employee
  module ManageRole
    extend ActiveSupport::Concern

    def manage_admin_role!
      role_id = Role.where(name: "admin").first.id
      if has_role?(:admin)
        remove_admin_role(role_id)
      else
        add_admin_role(role_id)
      end
      reload
    end

    def remove_admin_role(role_id)
      employees_roles.where(role_id: role_id).destroy_all
    end

    def add_admin_role(role_id)
      employees_roles.create(role_id: role_id)
    end
  
  end
end

app/models/employee.rb
require 'soft_deletion'

class Employee < ActiveRecord::Base
  # FIXME this devise method will move into concerns employee/devisable.rb, facing some issue, need to look into it and then fix.
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  include Devisable
  include ManageRole
  
  has_soft_deletion :default_scope => true
  ROLES = %w[super_admin admin employee]

  validates :email, format: { :with => EMAIL_REGEX }, allow_blank: true
  validates :employee_id, :presence => { message: 'ID cannot be blank'}, uniqueness: { scope: :company_id, message: "ID has already being taken" }
  validates :employee_id, numericality: { :only_integer => true, :greater_than => 0, :message => "ID must be positive"}, allow_blank: true
  validates :name, presence: true
    
  has_many :employees_roles, dependent: :destroy
  has_many :roles, through: :employees_roles
  has_many :assignments
  has_many :assets, through: :active_assignments
  has_many :comments, :foreign_key => 'commenter_id'
  has_many :returned_assignments, -> { where.not(date_returned: nil) }, class_name: 'Assignment'
  has_many :active_assignments, -> { where(date_returned: nil).order("asset_employee_mappings.date_issued desc") }, class_name: 'Assignment'
  has_many :tickets
  has_many :file_uploads
  belongs_to :company

  scope :enabled, lambda { |company|  Employee.where(company_id: company) }
  scope :disabled, lambda { |company|  unscoped.where.not(deleted_at: nil).where(company_id: company.id) } 

  delegate :name, to: :company, prefix: true

  alias_attribute :admin, :is_admin
  before_create :assign_default_role

  def can_be_disabled?
    assignments.all? { |a| a.returned? }
  end
  
  def enabled?
    !deleted_at?
  end        

  def disabled?
    !enabled?
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def has_any_role?
    roles.any? { |r| Employee::ROLES.include?(r.name)}
  end
  
  private
    def assign_default_role
      self.roles << Role.where(name: "employee").first
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  autocomplete :employee, :name, :full => true, :limit => 1000

  before_filter :find_employee, :only => [:edit, :update, :disable]
  before_filter :find_unscoped_employee, :only => :show
  authorize_resource
  skip_authorize_resource only: [:edit_password, :update_password]
  
  def index
    if params[:type].blank?
      @employees = Employee.with_deleted{ Employee.where(company_id: current_company.try(:id)) }
    else
      @employees = Employee.send(params[:type], current_company)
    end
    @employees = @employees.includes(:assignments, :roles).order('name asc').paginate :page => params[:page], :per_page => 100
  end

  def show
    @history = @employee.returned_assignments.includes(asset: :asset_type).order('asset_employee_mappings.date_returned desc')
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = current_company.employees.new params_employee
    if @employee.save
      redirect_to employees_path, :notice => "Employee #{@employee.name} has been created successfully"
    else
      render :action => "new" 
    end   
  end

  def edit
  end

  def update
    unless request.xhr?
      if @employee.update_attributes(params_employee)
        redirect_to(@employee, :notice => "Employee #{@employee.name} has been updated successfully")
      else
        render :action => "edit"
      end
    else
      return flash.now[:notice] = "You can not disable yourself" if @employee == current_employee
      @employee.manage_admin_role!
      flash.now[:notice] = "#{@employee.name} #{@employee.has_role?(:admin) ? 'marked as admin' : 'is no longer admin'}"
    end
  end
    
  def enable
    employee = current_company.employees.with_deleted{ current_company.employees.where(:id => params[:id]).first }
    if employee.soft_undelete!
      redirect_to :back, :notice => "Employee #{employee.name} has been enabled successfully"
    else
      redirect_to :back, :alert => "Employee #{employee.name} has not been enabled successfully"
    end 
  end
  
  ## Used to soft delete the employees, will not let them delete if any asset is assigned to them
  def disable
    unless @employee.can_be_disabled?
      redirect_to :back, :alert => "First remove all assigned asset from #{@employee.name}"
    else
      @employee.soft_delete!  
      redirect_to :back, :notice => "Employee #{@employee.name} has been disabled successfully"
    end
  end

  def get_autocomplete_items(parameters)
    super(parameters).where(:company_id => current_company.id)
  end
  
  #to reset the password
  def edit_password
    @employee = current_employee
  end

  #to update the password
  def update_password
    @employee = current_employee
    if @employee.update_with_password(params_employee)
      redirect_to root_path
    else
      render :action => "edit_password"
    end
  end

  def assignment_report
    @employees = Employee.enabled(current_company).includes(active_assignments: :asset).order('name asc')
    @employees = @employees.paginate :page => params[:page], :per_page => 100 unless request.xhr?
    @employees
  end

  protected
  
  def find_employee
    @employee = current_company.employees.where(:id => params[:id]).first
    redirect_to root_path, :alert => "Could not find employee" unless @employee
  end

  def find_unscoped_employee
    @employee = Employee.unscoped.where(id: params[:id], company_id: current_company.try(:id)).includes(active_assignments: {asset: :asset_type}).first
    redirect_to root_path, :alert => "Employee not found for specified id" unless @employee
  end
  
  def params_employee
    params.require(:employee).permit(:name, :employee_id, :email, :current_password, :password, :password_confirmation)
  end 
  
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def show_history employee
    unless(employee.assignments.blank?)
      link_to "History", history_employee_path(employee), :class => 'btn'
    end
  end
  
  def show_disable_option emp
    unless emp.deleted?
      link_to 'Disable', disable_employee_path(emp), :method => :put, :class => 'btn btn-medium btn-danger', :disabled => emp == current_employee, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
    else
      link_to 'Enable', enable_employee_path(emp), :method => :put, :class => 'btn btn-medium btn-primary'
    end
  end

  def current_employee_or_employee_disabled?(employee)
    employee.id == current_employee.id || employee.disabled?
  end
  
end

app/views/employees/_assignment_history.html.erb
<% if @history.present? %>
  <b>Assignment History</b><br />
  <table class="table table-striped">
    <thead>
      <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Issued On</th>
      <th>Returned On</th>
      <th>Type</th>
      <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @history.each do |history| %>
      <tr>
        <td><%= history.asset_id %></td>
        <td><%= show_asset_name(history) %></td>
        <td width="120px"><%= date_to_string history.date_issued %></td>
        <td width="120px"><%= date_to_string history.date_returned %></td>
        <td><%= history.expected_return_date? ? "Temporary" : "Permanent" %></td>
        <td><%= history.returned? ? "Returned" : "Assigned" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <b>There is no assignment history</b>
<% end %>

app/views/employees/_detail_report.html.erb
<div><%= link_to 'Print', assignment_report_employees_path, id: 'printAssignmentReport', :class => "btn btn-medium btn-primary", :remote => true %></div><br style="clear:both"/><br style="clear:both"/>

<div id="printTableDiv">
<head><h3>Assignment Report</h3></head>
<table class="table table-striped" id="printTable">
  <thead>
    <tr>
      <th><span>Name</span><span class="assignmentReportHeader1">Assets</span><span class="assignmentReportHeader2">Issued On</span></th>

    </tr>
  </thead>
  <tbody>
    <% @employees.each do |emp| %>
      <tr>
        <% if emp.active_assignments.present? %>
          <td>
            <%= link_to emp.name, emp, id: "employeePrintName" %><br />
            <% emp.active_assignments.each do|assigment| %>
              <span class="assignedAssetName"><%= link_to assigment.asset.display_name, [assigment.asset.asset_type, assigment.asset] %> (<%= assigment.asset.barcode %>)</span>
              <span class="assignedAssetDate"><%= date_to_string(assigment.date_issued.to_date) %></span>
              <br />
            <% end %>
          </td>
        <% else %>  
          <td>
            <%= link_to emp.name, emp, id: "employeePrintName" %><br />
            <span class="assignedAssetName">There are no asset assigned</span>
          <td>
        <% end %>    
      </tr>
    <% end %>  
  </tbody>
</table>
</div>

app/views/employees/_form.html.erb
<%= form_for @employee, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => "shared/errors", :locals => { :obj => @employee } %>
  <div class="control-group">
    <%= f.label :employee_id, 'Employee Id', :class => 'control-label' %><span class="requiredField"><%= mark_required(@employee, 'employee_id') %></span>
    <div class="controls">
      <%= f.text_field :employee_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %><span class="requiredField"><%= mark_required(@employee, 'name') %></span>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %><span class="requiredField"><%= mark_required(@employee, 'email') %></span>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
     <%= link_to 'Cancel', request.referer %>
  </div>
<% end %>

app/views/employees/assignment_report.html.erb
<div id="assignmentReportIndex" >
  <div id="pageEnteriesInfoAssignment"><%= page_entries_info @employees, :model => 'Employees' %></div>
  <%= render :partial => "employees/detail_report" %>
  <div id='pagination'><%= will_paginate @employees %></div>
</div>
<div id="printAssignmentReportIndex" class="hidden">
</div>

app/views/employees/assignment_report.js.erb
$('div#printAssignmentReportIndex').html("<%= escape_javascript(render :partial => 'employees/detail_report')%>");
$('div#printAssignmentReportIndex #printTableDiv').printThis();
setTimeout(function(){$('div#printAssignmentReportIndex #printTableDiv').html("")},3000);

app/views/employees/edit.html.erb
<div class="page-header">
  <h2>Update <%=t '.title', :default => @employee.name %></h2>
</div>
<%= render :partial => 'form' %>

app/views/employees/edit_password.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "Update Password" %></h2>
</div>

<%= form_for(@employee, :url => update_password_employees_path , :method => :put, :html => { :class => 'form-horizontal' } ) do |f|%>
	<%= render :partial => "shared/errors", :locals => { :obj => @employee } %>
  <div class="control-group">
    <%= f.label :current_password, :class => 'control-label' %><span class="requiredField">*</span>
    <div class="controls">
      <%= f.password_field :current_password, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label t('.password', :default => t("helpers.labels.password")), :class => 'control-label' %><span class="requiredField">*</span>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label t('.password_confirmation', :default => t("helpers.labels.password_confirmation")), :class => 'control-label' %><span class="requiredField">*</span>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/index.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => (params[:type]) ? params[:type].humanize : "All" %> Employees</h2>
</div>
<div>
  <span>
    <%= link_to 'Add new Employee', new_employee_path, :class => 'btn btn-primary' %>
    <%= link_to "Disabled Employees", employees_path('disabled'), :class => "btn btn-primary #{class_name('employees', 'index', 'disabled')}" %>
    <%= link_to "Enabled Employees", employees_path('enabled'),  :class => "btn btn-primary #{class_name('employees', 'index', 'enabled')}" %>
  </span>
</div>
<% if @employees.present? %>
  <div id="pageEnteriesInfo" align='right'><%= page_entries_info @employees, :model => 'Employees' %></div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Admin</th>
        <th>Employee Id</th>
        <th>Name</th>
        <th>Email</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td>
            <%= form_for employee, :html => { :class => 'form-horizontal', :id => "adminStatusForm"  } do |f| %>
              <%= f.check_box :is_admin, {:checked => employee.has_role?(:admin), :disabled => current_employee_or_employee_disabled?(employee), :id => "adminCheckBox_#{employee.id}"} %>
              <%= f.hidden_field :name %>
            <% end %>
          </td>
          <td><%= employee.employee_id %></td>
          <td><%= link_to employee.name, employee_path(employee) %></td>
          <td><%= employee.email %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_employee_path(employee), :class => 'btn btn-medium' if employee.enabled? %> 
            <%= show_disable_option employee %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id='pagination' align='left'><%= will_paginate @employees %></div>
<% else %>
  <br />
  <strong>There are no <%= params[:type] ? params[:type].humanize : "" %> Employees</strong>
<% end %>

app/views/employees/new.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "New Employee" %></h2>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<% if @employee %>
  <div class="page-header">
    <h2><%=t '.title', :default => @employee.name %></h2>
  </div>

  <dl class="dl-horizontal">
    <dt><strong>Employee Id:</strong></dt>
    <dd><%= @employee.employee_id %></dd>
    <dt><strong>Name:</strong></dt>
    <dd><%= @employee.name %></dd>
    <dt><strong>Email:</strong></dt>
    <dd><%= @employee.email %></dd>
  </dl>

  <div class="form-actions">
    <%= link_to 'Back', request.referer, :class => "btn" %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_employee_path(@employee), :class => 'btn' if @employee.enabled? %>
    <%= show_disable_option @employee %> 
  </div>


  <% if @employee.active_assignments.present?  %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Asset Id</th>
          <th>Name</th>
          <th>Type</th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @employee.active_assignments.each do |assignment| %>
          <tr>
            <td><%= assignment.asset.id %></td>
            <td><%= link_to assignment.asset.name, [assignment.asset.asset_type, assignment.asset] %></td>
            <td><%= assignment.asset.try(:asset_type).try(:name) %></td>
            <td>
              <%= link_to 'Return Asset', return_asset_path(:type => "asset", :id => assignment.asset.id.to_s), :class => 'btn btn-medium btn-primary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      There is no assigned assets for <strong><%=t '.title', :default => @employee.name %></strong><br />
  <% end %><br />
  <%= render :partial => "assignment_history" %>
<% end %>

app/views/employees/update.js.erb
$('div.flashMessageDiv').html("<%= escape_javascript(render :partial => 'layouts/flash_message')%>")
<% if @employee.has_role?(:admin) %>
  $('#adminCheckBox_<%= @employee.id %>').attr('checked','checked');
<% else %>
  $('#adminCheckBox_<%= @employee.id %>').attr('checked',false);
<% end %>