config/routes.rb
Rails4::Application.routes.draw do
 
  resources :companies, :except => [:destroy, :show] do 
    member do 
      put :change_status
    end
  end

  scope(path: "(:current_company)") do 
    as :employee do
      match '/employee/confirmation' => 'confirmations#update', :via => :put, :as => :update_employee_confirmation
    end
    
    devise_for :employees, :controllers => { :confirmations => "confirmations" }
    
    get "employees(/:type)", :controller => :employees, :action => :index, :type => /enabled|disabled/, :as => :employees

    resources :employees, :except => :index do
      get :autocomplete_employee_name, :on => :collection
      get 'password/reset', :action => 'edit_password', :on => :collection
      put :update_password, :on => :collection
      get :assignment_report, :on => :collection
      member do
        put :disable
        put :enable
      end 
    end

    resources :assets, :path => "assets", :only => [:new, :create] do 
      member do 
        put :uploaded_files
      end
      collection do 
        get :autocomplete_tag_name
        get :autocomplete_assets_name
        get :autocomplete_asset_vendor
        get :autocomplete_asset_brand
      end
    end
    
    get "/assets(/:type)", to: "assets#index", :as => :assets_list

    resources :asset_types do 
      resources :assets do
        collection do
          get :change_form_content
          get :assign
        end
        member do
          delete :remove_tag
          put :retire_asset
        end 
        resources :assignments, :only => [:new, :create]
      end
    end

    resources :property_groups, :except => [:edit, :update] do 
      resources :properties, :only => [:create, :destroy]
    end


    resources :comments, :only => [:create, :destroy, :show]
    
    resources :asset_properties, :except => :index do 
      get :autocomplete_property_name, :on => :collection
    end

    resources :assignments do
      collection do
        get :change_aem_form
        get :populate_asset
      end
    end
    
    get "tickets(/:state)", :controller => :tickets, :action => :index, :state => /closed|open/, :as => :tickets
    get "/asset_types/:id/asset/:id/tickets", :to => "assets#tickets", :as => "asset_tickets"
    
    resources :tickets, :except => [:destroy, :edit, :update] do 
      member do 
        put :change_state
      end
      collection do 
        get :search
      end
    end
    resources :file_uploads, :only => :destroy  

    get "/:id/asset_properties", :to => "asset_properties#index", :as => "asset_properties_index"    
    get ":type/:id/return", :to => "assignments#return_asset", :as => "return_asset"
    get ":type/:id/histories", :to => "histories#index", :as => "histories"
    get 'show_tag', :to => "home#show_tag", :as => :show_tag
    get 'search', :to => "home#search", :as => :search
    get "asset_type/:asset_type_id/asset/:id/return", :to => "assignments#return_asset", :as => "return_asset_type_asset"

    authenticated :employee do
      root :to => "home#index"
    end

    unauthenticated :employee do
      devise_scope :employee do 
        get "/" => "devise/sessions#new"
      end
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :assign_variables, :only => :search

  def index
    return redirect_to companies_path if current_employee.has_role?(:super_admin)
    if current_employee.has_role?(:admin)
      @tags = current_company.tags.includes(:assets).paginate :page => params[:page], :per_page => 100
    else
      @assignments = current_employee.active_assignments.includes(:asset)
    end
  end
  
  #will search assets and employees and will filter it according to status, category, asset type, to , from, employee
  def search
    authorize! :read, current_employee
    return find_asset_from_barcode if params[:barcode].present?
    if params[:tag].present?
      find_assets_from_tag
    else
      if has_asset_attributes?
        @result = current_company.assets.search(@asset, @status, @category, @from, @to, @opt_employee)
      else
        find_employees
      end
    end
    @result = @result.paginate :page => params[:page], :per_page => 100 if @result.present? && !params[:print]
    @result
  end
  
  #will show assets in  the tags in the home page - Using AJAX
  def show_tag
    authorize! :read, current_employee
    @tag = Tag.where(:id => params[:tag_id]).first
    @assets = @tag.assets.paginate :page => params[:page], :order => 'created_at asc', :per_page => 100
  end

  private
    def find_asset_from_barcode
      @asset = Asset.where(barcode: params[:barcode]).first
      redirect_to [@asset.asset_type, @asset] if @asset
      flash.now[:alert] = "No Asset found with barcode: #{params[:barcode]}"
    end

    def find_assets_from_tag
      tag = current_company.tags.where(name: params[:tag]).first
      @result = tag.assets if tag
    end

    def find_employees
      if is_numeric?(params[:employee])
        @result = current_company.employees.where("employees.employee_id = ?", @opt_employee) 
      else
        @result = current_company.employees.where("employees.name like ?", "%#{@opt_employee}%")
      end
    end

    def has_asset_attributes?
      @asset.present? || @category.present? || @status.present? || @to.present? || @from.present?
    end

    def assign_variables
      params[:employee] = params[:employee].to_i if params[:employee] && is_numeric?(params[:employee])
      @asset, @opt_employee, @status, @category, @to, @from = params[:asset],  params[:employee], params[:status], params[:category], params[:to], params[:from]  
    end

    def is_numeric?(obj) 
      obj.to_s.match(IS_NUMERIC) ? true : false
    end
    
end

app/helpers/home_helper.rb
module HomeHelper

	def tag_class tag
		tag_count = tag.assets.size
		if(tag_count == 1)
			"TagSizeOne TagSpan"
		elsif(tag_count == 2)
			"TagSizeTwo TagSpan"
		elsif(tag_count == 3)
			"TagSizeThree TagSpan"
		elsif(tag_count == 4)
			"TagSizeFour TagSpan"
		else			
			"TagSizeBig TagSpan"
		end	
	end
	
end

app/views/home/_search_details.html.erb
<table class="table table-striped table-bordered" id="searchTable">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Status</th>
      <th>Barcode</th>
      <th>Serial Number</th>
      <th>Purchase Date</th>
    </tr>
  </thead>  
  <tbody>
    <% @result.each do |result| %>
      <tr>
        <td><%= result.id %></td>
        <td><%= link_to result.name, [result.asset_type, result] %></td>
        <td><%= result.status %></td>
        <td><%= result.barcode %></td>
        <td><%= result.serial_number %></td>
        <td><%= date_to_string(result.purchase_date.to_date) %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

app/views/home/_search_result.html.erb
<% if @result.present? %>
  <div class="page-header">
    <h2><%=t '.title', :default => "Search result" %></h2>
  </div>
  <div id="pageEnteriesInfo" style="float:left;display:inline;"><%= page_entries_info @result, :model => @result.first.class.to_s %></div>
  <span id="printSearchResultLink"><%= link_to 'Print', search_path(params.deep_dup.merge!(print: true)), id: 'printSearchReport', :class => "btn btn-medium btn-primary", :remote => true %></span>
  <br /><br />
  <% if @result.first.kind_of?(Employee) %>
    <% @result.each do |result| %>
      <div><%= link_to "#{result.employee_id} #{result.name}", result %></div>  
    <% end %> 
  <% else %>
    <%= render :partial => "search_details" %>
  <% end %>
  <div id='pagination' align='left'><%= will_paginate @result %></div>
  <script> $('.pagination a').attr('data-remote', 'true'); </script>
<% else %>
  <strong>There are no matching records</strong>
<% end %>

<script>

</script>

app/views/home/_show_tags.html.erb
<h3 class="showTagResult">Assets Tagged with Tag - <%= @tag.name %></h3>

<div id="pageEnteriesInfo" align='right'><%= page_entries_info @assets, :model => 'Asset' %></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Asset Id</th>
      <th>Name</th>
      <th>Status</th>
      <th>Assigned To</th>
    </tr>
  </thead>
  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.id %></td>
        <td><%= link_to asset.display_name, [asset.asset_type, asset] %></td>
        <td><%= asset.status.capitalize %></td>
        <td><%= asset.status == "Assigned" ? (link_to asset.assigned_employee.name, asset.assigned_employee) : "-" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id='pagination'><%= will_paginate @assets %></div>

<script>$('.pagination a').attr('data-remote', 'true'); </script>

app/views/home/index.html.erb
<% if @tags %>
  <div id="progressContainer" align="center"></div>
  <div class="page-header">
    <h2><%=t '.title', :default => "All Tags"  %></h2>
  </div>
  <% unless @tags.empty? %>
    <div class='TagList'>
      <% @tags.each do |tag| %>
        <% if tag.assets.present? %>
          <span class='<%= tag_class tag  %>' onclick="showTag(<%= tag.id %>);">
            <%= tag.name.humanize %>
            <%= hidden_field_tag('url_for_show_tag', show_tag_path) %>
          </span>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <br /> <strong>There are no tags created yet  </strong>
  <% end %>
  <div id="searchBox"></div>
<% else %>
  <% if @assignments && @assignments.present? %>
    <div class="header">
      <h2>Assets Assigned to You</h2>
    </div>
    <div class="assetAssignedToEmployee">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Issued On</th>
          </tr>
        </thead>
        <tbody>
          <% @assignments.each do|assignment| %>
            <tr>
              <td width="60%"><%= link_to assignment.asset.display_name, asset_type_asset_path(assignment.asset.asset_type, assignment.asset) %></td>

              <td><%= date_to_string(assignment.date_issued) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>  
  <div class="employeeInfo">
    <dl class="dl-horizontal">
      <dt><strong>Employee Id:</strong></dt>
      <dd><%= current_employee.employee_id %></dd>
      <dt><strong>Name:</strong></dt>
      <dd><%= current_employee.name %></dd>
      <dt><strong>Email:</strong></dt>
      <dd><%= current_employee.email %></dd>
    </dl>
  </div>

<% end %>

app/views/home/search.html.erb
<div id="progressContainer" align="center"></div>
<div class="page-header">
  <h2><%=t '.title', :default => "Search" %></h2>
</div>
<%= form_tag search_path, :remote => true, :method => :get do %>
  <div class="control-group">
    <%= label_tag :asset, nil, :class => 'control-label, boldLableName' %>
    <div class="controls">
      <%= text_field_tag 'asset', '', :class => 'tags_with_autocomplete', 'data-autocompleteUrl' =>autocomplete_assets_name_assets_path, :size => 75,  :placeholder => "Name Or Serial Number" %>

      <%= select_tag "status", options_for_select(Asset::STATUS), :prompt => "Select Status" %> 
      <%= select_tag "category", options_for_select(select_category), :prompt => "Select Asset Type" %>
    </div>
  </div>
  <div class="control-group">
    <b>Purchase between</b>
    <div class="controls">
      <%= text_field_tag :from, nil, :class => "text_field", :readonly => true, :placeholder => "from" %> <span id="hyphenOnSearchPage">-</span>
      <%= text_field_tag :to, nil,:class => "text_field",:readonly => true, :placeholder => "to" %>
    </div>
  </div>  

  <div class="control-group">
    <%= label_tag :employee, nil, :class => 'control-label, boldLableName' %>
    <div class="controls">
      <%= autocomplete_field_tag 'employee', '', autocomplete_employee_name_employees_path, :size => 75 %><span class="hintText">Hint: Name / Employee Id</span>
     </div>
  </div>
  <strong>Or Search Assets By Tag</strong>
  <div class="control-group">
    <%= label_tag :tag_name, nil, :class => 'control-label, boldLableName' %>
    <div class="controls">
      <%= autocomplete_field_tag 'tag', '', autocomplete_tag_name_assets_path, :size => 75 %>
     </div>
  </div>
  <strong>Or Search Assets By BarCode</strong>
  <div class="control-group">
    <%= label_tag :barcode, nil, :class => 'control-label, boldLableName' %>
    <div class="controls">
      <%= text_field_tag 'barcode', nil,:autocomplete => 'off' %><span class="barcodeHintText">Hint: Focus should be on field before scanning the barcode.<br /><i>First four digits represents asset type id and rest 6 represents asset id</i></span>
     </div>
  </div>
  
  <div class="form-actions">
    <%= submit_tag "Search", :class => 'btn btn-primary', :id => "searchFormButton", data: { disable_with: "Please wait..." } %>
  </div>
	<div id="searchBox"></div>
  <div id="printSearchResult" class="hidden"></div>
<% end %>
<script>
  //autosuggest asset name
  $('.tags_with_autocomplete').autocomplete({
    minLength: 1,
    source: function(request, response) {
      $.ajax({
        url: $('.tags_with_autocomplete').data('autocompleteurl'),
        dataType: "json",
        data: {
          query: request.term
        },
        success: function(data) {
          response(data);
        }
      });
    }
  }).data("uiAutocomplete")._renderItem = function (ul, item) {
    return $("<li></li>").data("item.autocomplete", item).append("<a>" + item.value + "<div style='font-size:12px;color:grey'>(Serial# " + item.serial_number + ")</div>" + "</a>").appendTo(ul);
  };
</script>

app/views/home/search.js.erb
<% unless params[:print] %>
  $("#searchBox").html("<%= escape_javascript(render :partial => 'search_result') %>");
  $("#searchBox").addClass("searchBox");
  $('html, body').animate({ scrollTop: $('#searchBox').offset().top }, 'slow');
  $('.alert').remove();
<% else %>
  $('#printSearchResult').html("<%= escape_javascript(render :partial => 'search_details') %>");
  $('#printSearchResult table').printThis();
<% end %>

app/views/home/show_tag.js.erb
$("#searchBox").html("<%= escape_javascript(render :partial => "show_tags") %>")
$("#searchBox").addClass("searchBox");