config/routes.rb
Rails4::Application.routes.draw do
 
  resources :companies, :except => [:destroy, :show] do 
    member do 
      put :change_status
    end
  end

  scope(path: "(:current_company)") do 
    as :employee do
      match '/employee/confirmation' => 'confirmations#update', :via => :put, :as => :update_employee_confirmation
    end
    
    devise_for :employees, :controllers => { :confirmations => "confirmations" }
    
    get "employees(/:type)", :controller => :employees, :action => :index, :type => /enabled|disabled/, :as => :employees

    resources :employees, :except => :index do
      get :autocomplete_employee_name, :on => :collection
      get 'password/reset', :action => 'edit_password', :on => :collection
      put :update_password, :on => :collection
      get :assignment_report, :on => :collection
      member do
        put :disable
        put :enable
      end 
    end

    resources :assets, :path => "assets", :only => [:new, :create] do 
      member do 
        put :uploaded_files
      end
      collection do 
        get :autocomplete_tag_name
        get :autocomplete_assets_name
        get :autocomplete_asset_vendor
        get :autocomplete_asset_brand
      end
    end
    
    get "/assets(/:type)", to: "assets#index", :as => :assets_list

    resources :asset_types do 
      resources :assets do
        collection do
          get :change_form_content
          get :assign
        end
        member do
          delete :remove_tag
          put :retire_asset
        end 
        resources :assignments, :only => [:new, :create]
      end
    end

    resources :property_groups, :except => [:edit, :update] do 
      resources :properties, :only => [:create, :destroy]
    end


    resources :comments, :only => [:create, :destroy, :show]
    
    resources :asset_properties, :except => :index do 
      get :autocomplete_property_name, :on => :collection
    end

    resources :assignments do
      collection do
        get :change_aem_form
        get :populate_asset
      end
    end
    
    get "tickets(/:state)", :controller => :tickets, :action => :index, :state => /closed|open/, :as => :tickets
    get "/asset_types/:id/asset/:id/tickets", :to => "assets#tickets", :as => "asset_tickets"
    
    resources :tickets, :except => [:destroy, :edit, :update] do 
      member do 
        put :change_state
      end
      collection do 
        get :search
      end
    end
    resources :file_uploads, :only => :destroy  

    get "/:id/asset_properties", :to => "asset_properties#index", :as => "asset_properties_index"    
    get ":type/:id/return", :to => "assignments#return_asset", :as => "return_asset"
    get ":type/:id/histories", :to => "histories#index", :as => "histories"
    get 'show_tag', :to => "home#show_tag", :as => :show_tag
    get 'search', :to => "home#search", :as => :search
    get "asset_type/:asset_type_id/asset/:id/return", :to => "assignments#return_asset", :as => "return_asset_type_asset"

    authenticated :employee do
      root :to => "home#index"
    end

    unauthenticated :employee do
      devise_scope :employee do 
        get "/" => "devise/sessions#new"
      end
    end
  end
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  include Shared::RestrictiveDestroy

  has_associated_audits
  auto_strip_attributes :name

  validates :name, :email, presence: true
  validates :name, :email, uniqueness: true, allow_blank: true
  validates :website, uniqueness: true, :if => :website?
  validates :email, :format => { :with => EMAIL_REGEX }, :allow_blank => true
  validates :website, :format => { :with => URI::regexp(%w(http https)) }, :allow_blank => true

  has_many :assets
  has_many :employees
  has_many :tags
  has_many :properties
  has_many :property_groups
  has_many :asset_types
  has_many :ticket_types
  has_many :tickets
  has_many :admins, -> { joins(:roles).where(roles: {name: "admin"})}, class_name: "Employee"

  after_create :create_default_admin

  has_permalink :firstname, :unique => true
  
  def enabled?
    status?
  end

  def disabled?
    !enabled?
  end

  def firstname
    name.split()[0] if name
  end

  private
  
    def create_default_admin
      employee = employees.new(name: name, email: email, employee_id: 1, is_admin: true)
      employee.roles = [Role.where(name: "admin").first]
      employee.save
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_filter :verify_current_company
  
  before_action :find_company, :only => [:edit, :update, :change_status]
  authorize_resource  
  
  def index
    @companies = Company.all.paginate(page: params[:page], per_page: 100)
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create 
    @company = Company.new params_company
    if @company.save
      redirect_to companies_path, :notice => "Company #{@company.name} has been created successfully"
    else
      render 'new'
    end
  end

  def update
    if @company.update_attributes(params_company)
      redirect_to companies_path, :notice => "Company #{@company.name} has been updated successfully"
    else
      render :action => "edit"
    end
  end

  def change_status
    @company.toggle!(:status)
    redirect_to companies_path, :notice => "Company #{@company.name} has been #{@company.enabled? ? 'enabled' : 'disabled'} successfully"
  end

  private

    def find_company
      @company = Company.where(permalink: params[:id]).first
      redirect_to companies_path, :alert => "Company not found for specified id" unless @company
    end

    def params_company
      params.require(:company).permit(:name, :email, :website)
    end
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => 'form-horizontal' } do |f| %>
	<%= render :partial => "shared/errors", :locals => { :obj => @company } %>
	<div class="control-group">
    <%= f.label :name, :class => 'control-label' %><span class="requiredField"><%= mark_required(@company, 'name') %></span>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %><span class="requiredField"><%= mark_required(@company, 'email') %></span>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary', :onclick => "fillTagContent()" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), companies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "Edit Company" %></h2>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "All Companies"  %></h2>
</div>
<div><%= link_to 'Add Company', new_company_path, :class => 'btn btn-primary' %></div>
<div id="pageEnteriesInfo" align='right'><%= page_entries_info @companies, :model => 'Companies' %></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Website</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.email %></td>
        <td><%= link_to company.website, company.website, :target => "_blank" %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(company), :class => 'btn btn-medium' %>
          <%= link_to (company.enabled? ? t(:disable) : t(:enable)), change_status_company_path(company), :method => :put, :class => "btn #{company.enabled? ? 'btn-danger' : 'btn-primary'}", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id='pagination' align='left'><%= will_paginate @companies %></div>

app/views/companies/new.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "Add Company" %></h2>
</div>
<%= render :partial => 'form' %>