config/routes.rb
Rails4::Application.routes.draw do
 
  resources :companies, :except => [:destroy, :show] do 
    member do 
      put :change_status
    end
  end

  scope(path: "(:current_company)") do 
    as :employee do
      match '/employee/confirmation' => 'confirmations#update', :via => :put, :as => :update_employee_confirmation
    end
    
    devise_for :employees, :controllers => { :confirmations => "confirmations" }
    
    get "employees(/:type)", :controller => :employees, :action => :index, :type => /enabled|disabled/, :as => :employees

    resources :employees, :except => :index do
      get :autocomplete_employee_name, :on => :collection
      get 'password/reset', :action => 'edit_password', :on => :collection
      put :update_password, :on => :collection
      get :assignment_report, :on => :collection
      member do
        put :disable
        put :enable
      end 
    end

    resources :assets, :path => "assets", :only => [:new, :create] do 
      member do 
        put :uploaded_files
      end
      collection do 
        get :autocomplete_tag_name
        get :autocomplete_assets_name
        get :autocomplete_asset_vendor
        get :autocomplete_asset_brand
      end
    end
    
    get "/assets(/:type)", to: "assets#index", :as => :assets_list

    resources :asset_types do 
      resources :assets do
        collection do
          get :change_form_content
          get :assign
        end
        member do
          delete :remove_tag
          put :retire_asset
        end 
        resources :assignments, :only => [:new, :create]
      end
    end

    resources :property_groups, :except => [:edit, :update] do 
      resources :properties, :only => [:create, :destroy]
    end


    resources :comments, :only => [:create, :destroy, :show]
    
    resources :asset_properties, :except => :index do 
      get :autocomplete_property_name, :on => :collection
    end

    resources :assignments do
      collection do
        get :change_aem_form
        get :populate_asset
      end
    end
    
    get "tickets(/:state)", :controller => :tickets, :action => :index, :state => /closed|open/, :as => :tickets
    get "/asset_types/:id/asset/:id/tickets", :to => "assets#tickets", :as => "asset_tickets"
    
    resources :tickets, :except => [:destroy, :edit, :update] do 
      member do 
        put :change_state
      end
      collection do 
        get :search
      end
    end
    resources :file_uploads, :only => :destroy  

    get "/:id/asset_properties", :to => "asset_properties#index", :as => "asset_properties_index"    
    get ":type/:id/return", :to => "assignments#return_asset", :as => "return_asset"
    get ":type/:id/histories", :to => "histories#index", :as => "histories"
    get 'show_tag', :to => "home#show_tag", :as => :show_tag
    get 'search', :to => "home#search", :as => :search
    get "asset_type/:asset_type_id/asset/:id/return", :to => "assignments#return_asset", :as => "return_asset_type_asset"

    authenticated :employee do
      root :to => "home#index"
    end

    unauthenticated :employee do
      devise_scope :employee do 
        get "/" => "devise/sessions#new"
      end
    end
  end
  
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  include Barcode
  include Taggable
  include ManagePropertyGroups
  include StatusMachine
  include Shared::RestrictiveDestroy
  include Commentable

  audited only: [:name, :status, :deleted_at, :vendor, :brand, :serial_number, :purchase_date, :description,:cost,:additional_info], associated_with: :company, on: [:update, :destroy]
  default_scope { where(deleted_at: nil) }

  validates :name, :status, :cost, :asset_type_id, :vendor, :purchase_date, presence: true
  validates :cost, numericality: true, length: {:maximum=> 10}, allow_blank: true 
  validates :serial_number, presence: true, uniqueness: true
  validates :brand, presence: true, on: :create
  validates :purchase_date, :date => { :before => Proc.new { Time.current } }, allow_blank: true  
  
  has_many :file_uploads
  has_many :assignments
  has_many :employees, :through => :assignments
  has_many :asset_properties, dependent: :destroy
  has_many :properties, through: :asset_properties
  has_many :property_groups, -> { group "property_group_id" }, through: :asset_properties 
  has_many :active_assignments, -> { where(date_returned: nil) }, class_name: 'Assignment'
  has_many :tickets, lambda{ joins(:ticket_type).where.not(ticket_types: {name: "New Hardware"}) }, class_name: 'Ticket'
  
  belongs_to :company
  belongs_to :asset_type

  accepts_nested_attributes_for :file_uploads, :allow_destroy => true, reject_if: proc { |attributes| attributes['file'].blank? && attributes['description'].blank?}
  
  scope :retired_assets, lambda { |company| unscoped.where.not(deleted_at: nil).where(company_id: company.id) }

  before_update :restrict_update, :if => "retired?"

  def self.search(asset, status, category, from, to, employee)
    conditions = self.search_conditions(asset, status, category, from, to)
    result = self.where(conditions).includes(:asset_type)
    if employee.present? 
      result = result.joins(assignments: :employee).where("asset_employee_mappings.date_returned is NULL")
      if employee.kind_of?(Integer)
        result = result.where(employees: {employee_id: employee}) 
      else
        result = result.where(employees: {name: employee}) 
      end
    end
    result
  end 
  
  # Will return an active relation of employees to whome any asset is asssigned  
  def assigned_employee
    assignments.last.try(:employee) 
  end

  def active_assigned_employee
    active_assignments.last.try(:employee) 
  end
  
  def retired?
    deleted_at.present?
  end

  def display_name
    "#{self.id}-#{self.name}"
  end

  def has_tickets?
    tickets.present?
  end

  private    
    
    def restrict_update
      return false unless changes.keys.include?("deleted_at")
    end

    def self.search_conditions(asset, status, category, from, to)
      conditions = ['1']
      if asset.present?
        conditions[0] += " AND (assets.name like ? OR assets.serial_number like ?)"
        conditions.push("%#{asset}%").push("%#{asset}%")
      end
      if category.present?
        conditions[0] += " AND assets.asset_type_id = ?" 
        conditions << category
      end
      if status.present?
        conditions[0] += " AND assets.status = ?"
        conditions << status
      end
      if to.present?
        conditions[0] += " AND DATE(purchase_date) <= ?" 
        conditions << to.to_date
      end
      if from.present?
        conditions[0] += " AND DATE(purchase_date) >= ?"
        conditions << from.to_date
      end
      conditions 
    end

end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
  include RestrictiveDestroy
  
  belongs_to :company 
  has_many :asset_type_property_groups, dependent: :destroy
  has_many :property_groups, through: :asset_type_property_groups
  has_many :assets
  
  validates :name, presence: true, uniqueness: { scope: :company_id }
  accepts_nested_attributes_for :asset_type_property_groups, allow_destroy: true

end

app/models/concerns/asset/manage_property_groups.rb
class Asset     
  module ManagePropertyGroups
    extend ActiveSupport::Concern

    included do
      before_create :assign_property_groups
    end
     
    def assign_property_groups
      if asset_type.present?
        asset_type.property_groups.each do |property_group|
          self.properties << property_group.properties if  property_group.properties.present?
        end
      end 
    end

  end
end

app/models/concerns/asset/status_machine.rb
class Asset     
  module StatusMachine
    extend ActiveSupport::Concern

    included do
      STATUS = {"Operational" => 'operational', "Recieved" => 'recieved', "Spare" => 'spare', "Repair" => 'repair', "Assigned" => 'Assigned' }
      scope :assignable, -> { where.not(status: [STATUS["Assigned"], STATUS["Repair"]]) }     
    end
    
    def can_retire?
      status != STATUS["Assigned"]
    end
    
    def assignable?
      ![STATUS["Assigned"], STATUS["Repair"]].include?(status) && !retired?
    end

    def mark_spare!
      update_attributes(:status => STATUS["Spare"])
    end

    def assign! 
      update_attributes(:status => STATUS["Assigned"])
    end
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  autocomplete :tag, :name, :full => true, :limit => 1000
  autocomplete :asset, :brand, :full => true, :limit => 1000
  autocomplete :asset, :vendor, :full => true, :limit => 1000

  before_action :find_asset, :only => [:edit, :update, :retire_asset, :remove_tag]
  before_action :find_unscoped_asset, :only => [:uploaded_files, :tickets, :show]

  authorize_resource 
  
  def index
    if params[:asset_type_id].present?
      @assets = current_company.assets.where(asset_type_id: params[:asset_type_id])
    elsif params[:type] == 'retired'
      @assets = Asset.retired_assets(current_company)
      @assets = @assets.order('id asc') unless params[:sort]
    else
      @assets = current_company.assets
    end
    @assets = @assets.order(params[:sort]) if params[:sort]
    @assets = @assets.includes(:asset_type, :assignments, :active_assignments => :employee).paginate(page: params[:page], per_page: 100)
  end
  
  def show
    @comments = @asset.comments.includes(:commenter).order("created_at desc")
    @comment = @asset.comments.build 
    @asset_properties = @asset.asset_properties.includes(:property)
    if request.xhr? && params[:query] == 'history'
      @audits = @asset.audits.includes(:admin).order('audits.created_at desc')
      @property_audits = Audited::Adapters::ActiveRecord::Audit.where(auditable_type: "AssetProperty", auditable_id: @asset.asset_properties.collect(&:id)).includes(:associated).order('audits.created_at desc')
    end
  end

  def new
    find_asset_type if params[:asset_type_id]
    @asset = Asset.new
    @file_uploads = @asset.file_uploads.build
  end
  
  def create
    @asset = current_company.assets.build params_asset
    if @asset.save
      redirect_to [@asset.asset_type, @asset], :notice => "#{@asset.name} has been created successfully"
    else
      find_asset_type if params[:asset_type_id]
      @file_uploads = @asset.file_uploads.build if @asset.file_uploads.blank?
      render :action => "new"
    end     
  end
    
  def edit
    @asset_type = @asset.asset_type
    @file_uploads = @asset.file_uploads.build
  end

  def update
    if @asset.update_attributes(params_asset)
      @asset.file_uploads.build
      respond_to do |format|
        format.js {flash.now[:notice] = "File uploaded successfully"}
        format.html { redirect_to [@asset.asset_type, @asset], :notice => "#{@asset.name} has been updated successfully" }
      end
    else
      unless request.xhr?
        @asset_type = @asset.asset_type
        @file_uploads = @asset.file_uploads.build if @asset.file_uploads.blank?
        render :action => "edit"
      end
    end
  end

  def retire_asset
    return redirect_to :back, :alert => "Asset is assigned, first return then retire it" unless @asset.can_retire?

    if @asset.update_attribute(:deleted_at, Time.now)
      redirect_to [@asset.asset_type, @asset], :notice => "#{@asset.name} has been retired successfully"
    else
      redirect_to [@asset.asset_type, @asset], :alert => "There is some problem, Please contact support"
    end
  end
  
  def get_autocomplete_items(parameters)
    result = super(parameters).where(:company_id => current_company.id)
    if parameters[:method] == :vendor
      result = result.group('assets.vendor') 
    elsif parameters[:method] == :brand 
      result = result.group('assets.brand') 
    end
    result
  end

  def remove_tag
    @tag = Tag.where(id: params[:tag_id]).first
    if @tag && @asset.remove_tags(@tag.id) 
      flash.now[:notice] = "Tag #{@tag.name} has been removed successfully"
    else
      flash.now[:alert] = "Tag could not be removed"
    end
  end

  def uploaded_files
    @file_uploads = @asset.file_uploads.build
  end

  def tickets
    @tickets = @asset.tickets.includes(:ticket_type, :employee, :asset).order("tickets.created_at desc").paginate(page: params[:page], per_page: 100)
  end

  def autocomplete_assets_name
    names = Asset.select([:name, :serial_number]).where("(name LIKE ? OR serial_number like ?) AND company_id = ?", "%#{params[:query]}%", "%#{params[:query]}%", current_company.id)
    result = names.collect do |t|
      { value: t.name,
       serial_number: t.serial_number
     }
    end
    render json: result
  end

  private
  
    def find_asset
      @asset = current_company.assets.where(id: params[:id]).first
      redirect_to root_path, :alert => "Record not found" unless @asset
    end

    def find_unscoped_asset
      @asset = Asset.unscoped.where(company_id: current_company.id, id: params[:id]).first
      redirect_to root_path, :alert => "Record not found" unless @asset
    end

    def find_asset_type
      @asset_type = current_company.asset_types.where(id: params[:asset_type_id]).first
    end

    def params_asset
      params.require(:asset).permit(:name, :status, :cost, :serial_number, :purchase_date, :brand, :vendor, :asset_type_id, :tags_field, :description, :additional_info, :currency_unit, :company_id, :file_uploads_attributes => [:file, :description, :id, :_destroy, :employee_id])
    end

end

app/helpers/assets_helper.rb
module AssetsHelper
  def show_name type
    return AssetType.where(id: params[:asset_type_id]).first.try(:name).try(:pluralize) if params[:asset_type_id].present?
    return "Retired Assets" if type == "retired"
    "Assets"
  end

  def show_status asset
    if(asset.status == "Assigned")
      "Assigned to #{link_to asset.assigned_employee.name, asset.assigned_employee}".html_safe
    else
      asset.status.capitalize
    end
  end

  def show_status_field f
    if @asset.status == "Assigned"
      "Assigned"
    else
      if @asset.new_record?
        f.select(:status, options_for_select(Asset::STATUS.to_a - [["Recieved", "recieved"], ["Assigned", "Assigned"]], @asset.status), :include_blank => "- Select -")
      else
        f.select(:status, options_for_select(Asset::STATUS.to_a - [["Assigned", "Assigned"]], @asset.status), :include_blank => "- Select -")
      end
    end
  end

  def show_category asset, f
    unless asset.new_record?
      asset.asset_type.try(:name) || 'No Type'
    else
      return @asset_type.try(:name) if params[:asset_type_id]
      asset_type_id = params[:asset][:asset_type_id] if params[:asset]
      f.select(:asset_type_id, options_for_select(current_employee.company.asset_types.collect{|asset_type| [asset_type.name, asset_type.id] }, asset_type_id), :include_blank => "- Select -") 
    end
  end

  def selected_asset_type
    return params[:asset][:asset_type_id] if params[:asset] && params[:asset][:asset_type_id]
    return @asset_type.try(:id) if @asset_type
  end


  def show_property_groups
    if @asset.asset_property_groups.present?
      current_employee.company.property_groups.where("id not in (?)",@asset.asset_property_groups.pluck(:property_group_id)).collect { |pg| [pg.name, pg.id] }
    else
      current_employee.company.property_groups.collect { |pg| [pg.name, pg.id] }
    end
  end

  def auditor_name(audit)
    admin = audit.admin.kind_of?(Employee) ? audit.admin : Employee.unscoped.where(id: audit.admin).first
    link_to admin.name, admin if admin
  end

  def sorting_condition(attr_name, conditions)
    if conditions.present?
      condition = conditions.split.include?('asc') ? 'desc' : 'asc'
      return attr_name + " IS NULL, " + attr_name + " " + condition if attr_name == "employees.name"
      return attr_name + " " + condition unless attr_name == "employees.name"
    else
      if attr_name == "employees.name"
        return attr_name + " IS NULL, " + attr_name + " asc" 
      else
        return attr_name + " asc" if attr_name != "id"
        return attr_name + " desc" if attr_name == "id"
      end
    end
  end

  def show_asset_name(history)
    return link_to history.asset.name, [history.asset.asset_type, history.asset] if history.asset.present?
    asset = Asset.unscoped.where(id: history.asset_id).includes(:asset_type).first
    return link_to asset.name, [asset.asset_type, asset] if asset.present?
  end

  def show_currency_symbol
    CURRENCY.collect do |currency|
      if currency[1] == '&#8377;'
        ['<span style="font-family:rupee;font-size:16px">&#8377;</span>'.html_safe, currency[1]]
      else
        [currency[1].html_safe, currency[1]] 
      end
    end
  end
  
  def uploaded_files 
    @asset.file_uploads.includes(:uploader)
  end

  def filter_paperclip_error(obj)
    msg = obj.errors.messages
    if msg[:"file_uploads.file"] && msg[:"file_uploads.file"].size == 1 && msg[:"file_uploads.file"] == ["can't be blank"]
      obj.errors.messages
    else
      obj.errors.messages.except!(:"file_uploads.file")
    end
  end


end

app/views/assets/_asset_details.html.erb
<tr>
  <td class="specs-key">Asset Id</td>
  <td class="specs-value"><%= @asset.id %></td>
</tr>
<tr>
  <td class="specs-key">Name</td>
  <td class="specs-value"><%= @asset.name %></td>
</tr>
<tr>
  <td class="specs-key">Type</td>
  <td class="specs-value"><%= @asset.asset_type.try(:name) || 'No Type' %></td>
</tr>
<tr>
  <td class="specs-key">Status</td>
  <td class="specs-value"><%= show_status @asset %></td>
</tr>
<tr>
  <td class="specs-key">Cost</td>
  <td class="specs-value"><%= number_to_currency(@asset.cost, :unit => (@asset.currency_unit == '&#8377;' ? '<span style="font-family:rupee;font-size:16px">R</span>' : @asset.currency_unit).html_safe) %></td>
</tr>
<tr>
  <td class="specs-key">Serial Number</td>
  <td class="specs-value"><%= @asset.serial_number %></td>
</tr>
<tr>
  <td class="specs-key">Brand</td>
  <td class="specs-value"><%= @asset.brand %></td>
</tr>  
<tr>
  <td class="specs-key">Vendor</td>
  <td class="specs-value"><%= @asset.vendor %></td>
</tr>  
<tr>
  <td class="specs-key">Purchase date</td>
  <td class="specs-value"><%= date_to_string @asset.purchase_date %></td>
</tr>  
<tr>
  <td class="specs-key">Description</td>
  <td class="specs-value"><%= @asset.description %></td>
</tr>  
<tr>
  <td class="specs-key">Additional Info</td>
  <td class="specs-value"><%= @asset.additional_info %></td>
</tr>
<tr>
  <td class="specs-key">Location</td>
  <td class="specs-value"><%= @asset.location %></td>
</tr>
<tr>
  <td class="specs-key">Tags</td>
  <td class="specs-value"><%= @asset.tags.present? ? @asset.tags.collect(&:name).join(', ') : '' %></td>
</tr>
<tr class="column-will-remove">
  <td class="specs-key column-will-remove">Operating System</td>
  <td class="specs-value column-will-remove"><%= @asset.operating_system %></td>
</tr>
<tr class="column-will-remove">
  <td class="specs-key column-will-remove">has_bag</td>
  <td class="specs-value column-will-remove"><%= @asset.has_bag %></td>
</tr>
<tr>
  <td class="specs-key">Barcode</td>
  <td class="specs-value" id='barcodeValue'><div id="barcodeImage"><%= @asset.get_barcode.html_safe %><br /><div id="barcodeLinkDiv" style="top: -13px;text-align: center;position: relative;display: inline-block;"><%= @asset.barcode %></div></div>
    <div><span id="printBarcode">Print</span><span id="printBarcodeInstructions">Printing Instructions</span></div>
    </td>
</tr>  

app/views/assets/_detail.html.erb
<div id="pageEnteriesInfo" align='right'><%= page_entries_info @assets, :model => 'Asset' %></div><br />
<span id="getUrlForSorting" data-url="<% request.url %>"></span>
<table class="table table-striped table-bordered tablesorter" id="sortAssetTable">
  <thead>
    <tr>
      <th width="9%" id="idSortAsset" class="header" data-sort="<%= sorting_condition('id', params[:sort]) %>" data-type="<%= params[:type] %>" data-page="<%= params[:page] || 1 %>">Asset Id</th>  
      <th id="nameSortAsset" class="header" data-sort="<%= sorting_condition('name', params[:sort]) %>" data-type="<%= params[:type] %>" data-page="<%= params[:page] || 1 %>">Name</th>   
      <th width="8%" id="statusSortAsset" class="header" data-sort="<%= sorting_condition('status', params[:sort]) %>" data-type="<%= params[:type] %>" data-page="<%= params[:page] || 1 %>">Status</th>
      <% unless params[:type] == 'retired' %>
        <th width="12%" id="employeeNameSortAsset" class="header" data-sort="<%= sorting_condition('employees.name', params[:sort]) %>" data-type="<%= params[:type] %>" data-page="<%= params[:page] || 1 %>">Assigned To</th> 
      <% end %>
      <th width="14%" id="purchasedateSortAsset" class="header" data-sort="<%= sorting_condition('purchase_date', params[:sort]) %>" data-type="<%= params[:type] %>" data-page="<%= params[:page] || 1 %>">Purchase Date</th>
      <th width="36%"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.id %></td>
        <td><%= link_to asset.name, [asset.asset_type, asset] %></td>
        <td><%= asset.status.capitalize %></td>
        <% unless params[:type] == 'retired' %>
          <td><%= asset.status == "Assigned" ? (link_to asset.active_assigned_employee.name, asset.active_assigned_employee) : "-" %></td>
        <% end %>
        <td><%= date_to_string(asset.purchase_date) %></td>
        <td>
          <% unless asset.retired? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_asset_type_asset_path(asset.asset_type_id, asset), :class => 'btn btn-medium' %>
            <%= link_to 'Return Asset', return_asset_path(:type => "asset", :id => asset.id.to_s), :class => 'btn return_asset', :disabled => !(asset.status == "Assigned") %>
          <% end %>
          <%= link_to "Assignment History", histories_path(:type => "asset", :id => asset.id), :class => 'btn' unless asset.assignments.blank? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id='pagination'><%= will_paginate @assets %></div>

app/views/assets/_limited_asset_details.html.erb
<tr>
  <td class="specs-key">Asset Id</td>
  <td class="specs-value"><%= @asset.id %></td>
</tr>
<tr>
  <td class="specs-key">Name</td>
  <td class="specs-value"><%= @asset.name %></td>
</tr>
<tr>
  <td class="specs-key">Type</td>
  <td class="specs-value"><%= @asset.asset_type.try(:name) || 'No Type' %></td>
</tr>
<tr>
  <td class="specs-key">Serial Number</td>
  <td class="specs-value"><%= @asset.serial_number %></td>
</tr>
<tr>
  <td class="specs-key">Brand</td>
  <td class="specs-value"><%= @asset.brand %></td>
</tr>  
<tr>
  <td class="specs-key">Description</td>
  <td class="specs-value"><%= @asset.description %></td>
</tr>  

app/views/assets/_property_group_form.html.erb
<%= form_for @asset.becomes(Asset), :method => :put, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => "shared/errors", :locals => { :obj => @asset } %>
  <div class="control-group">
    <%= f.label :property_groups, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:property_groups, show_property_groups, :include_blank => true) %>
      <%= f.submit "Add Property Group", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<div class="lightLine"></div>

app/views/assets/_uploaded_files_links.html.erb
<div id="errorMessages"></div>
<div id="fileFieldForAsset">
  <%= render :partial => "upload_form" %>
</div>

app/views/assets/edit.html.erb
<h2>Update <%=t '.title', :default => @asset.name  %></h2>
<div class="btn-group btn-group-justified">
  <%= link_to 'Detail', edit_asset_type_asset_path(@asset.asset_type_id, @asset), :remote => true, :class => "btn btn-default tab remote-true-ajax-call #{tag_class_name('assets', 'edit')}" %>
  <%= link_to "Properties", asset_properties_index_path(@asset.id), remote: true, :class => "btn btn-default tab remote-true-ajax-call" %>
</div>
<div id="assetFormAndProperties">
  <%= render :partial => 'form' %>
</div>

app/views/assets/index.html.erb
<div class="page-header">
  <h2><%= show_name(params[:type]) %></h2>
</div>
<div>
  <% if params[:asset_type_id] %>
    <%= link_to 'Add New Asset', new_asset_type_asset_path, :class => 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Add New Asset', new_asset_path, :class => 'btn btn-primary' unless params[:type] == 'retired' %>
  <% end %>
</div>
<% if @assets.present? %>
  <div id="sortedResultOfAssets">
    <%= render :partial => "detail" %>
  </div>
<% else %>
  <br /><strong>There are no records</strong>
<% end %>

app/views/assets/new.html.erb
<div class="page-header">
  <h2><%=t '.title', :default => "New Asset" %></h2>
</div>
<%= render :partial => 'form' %>

app/views/assets/show.html.erb
<div class="assetHeaderName">
  <h2><%= @asset.display_name %></h2>
  <% if can? :update, @asset %>
    <span><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_asset_type_asset_path(@asset.asset_type_id, @asset), :class => 'btn' unless @asset.retired? %></span>
    <span><%= link_to 'Return Asset', return_asset_type_asset_path(@asset.asset_type, @asset), :class => 'btn btn-danger' if @asset.status == "Assigned" %></span>
    <span><%= link_to 'Retire Asset', retire_asset_asset_type_asset_path(@asset.asset_type, @asset), :class => 'btn btn-danger', method: :put, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } unless @asset.status == "Assigned" || @asset.retired? %></span>
    <span><%= link_to 'Assign', new_asset_type_asset_assignment_path(@asset.asset_type, @asset), :class => "btn btn-primary #{class_name('assignments', 'new')}" if @asset.assignable? && !@asset.retired? %></span>
  <% end %>  
</div>
<div class="btn-group btn-group-justified">
  <% if can? :update, @asset %>
    <%= link_to 'Detail', asset_type_asset_path(@asset.asset_type, @asset, query: 'detail'), :remote => true, :class => "btn btn-default tab #{tag_class_name('assets', 'show')} remote-true-ajax-call" %>
    <%= link_to "Assignment History", histories_path(:type => "asset", :id => @asset.id), remote: true, :class => "btn btn-default tab remote-true-ajax-call" %>
    <%= link_to "Asset History", asset_type_asset_path(@asset.asset_type, @asset, query: 'history'), remote: true, :class => "btn btn-default tab remote-true-ajax-call" %>
    <%= link_to "Files", uploaded_files_asset_path(@asset), remote: true, method: :put, :class => "btn btn-default tab remote-true-ajax-call" %>
  <% end %>
  <% if current_employee.has_role?(:admin) %>
    <%= link_to 'Tickets', asset_tickets_path, remote: true, :class => 'btn btn-default tab remote-true-ajax-call' %>
  <% end %>  
</div>
<div id="showFlashMsg"></div>
<div id="assetShowPageInfo">
  <%= render :partial => "show_detail" %>
</div>

app/views/assets/show.js.erb
<% if defined?(@audits) || defined?(@property_audits) %>
  $('#assetShowPageInfo').html("<%= escape_javascript(render :partial => 'asset_history' )%>");
<% else %>
  $('#assetShowPageInfo').html("<%= escape_javascript(render :partial => 'show_detail' )%>");
<% end %>
endProgress();

app/views/assets/tickets.js.erb
<% if @tickets.present? %>
  $('#assetShowPageInfo').html("<%= escape_javascript(render :partial => 'tickets/details' )%>");
<% else %>
  $('#assetShowPageInfo').html("<br /><b>There are no tickets</b><br />");
<% end %>
endProgress();

app/views/assets/update.js.erb
<% if flash[:notice] %>
  $('div#showFlashMsg').html("<%= escape_javascript(render :partial => 'layouts/flash_message')%>")
  $("#fileFieldForAsset").html("<%= escape_javascript(render :partial => 'upload_form' )%>");
  $("#errorMessages").html("");
<% else %>  
  $("#errorMessages").html("<%= escape_javascript(render :partial => 'shared/errors', locals: {obj: @asset} )%>");
  $('div#showFlashMsg').html("")
<% end %>